const initialState = {
  products: [
    {
      id: '1',
      quantity: 1,
      type: 'Men',
      name: 'The North Face',
      category: 'Boots',
      price: 35,
      onSale: true,
      oldPrice: 55,
      outOfStock: false,
      image: '/images/products/men-boots.1.1.png',
      gallery: [
        '/images/products/men-boots.1.1.png',
        '/images/products/men-boots.1.2.png',
        '/images/products/men-boots.1.3.png',
        '/images/products/men-boots.1.4.png',
      ],
      starsRating: 4,
      size: ['40', '41', '42', '43'],
    },
    {
      id: '2',
      quantity: 1,
      type: 'Men',
      name: 'The North Face',
      category: 'Boots',
      price: 35,
      onSale: false,
      topSale: true,
      outOfStock: false,
      image: '/images/products/men-boots.2.1.png',
      starsRating: 4,
    },
    {
      id: '3',
      quantity: 1,
      type: 'Men',
      name: 'The North Face',
      category: 'Boots',
      price: 35,
      onSale: false,
      topSale: false,
      outOfStock: true,
      image: '/images/products/men-boots.4.1.jpg',
      gallery: [
        '/images/products/men-boots.4.1.jpg',
        '/images/products/men-boots.4.2.jpg',
        '/images/products/men-boots.4.3.jpg',
        '/images/products/men-boots.4.4.jpg',
      ],
      starsRating: 5,
    },
    {
      id: '4',
      quantity: 1,
      type: 'Men',
      name: 'The North Face',
      category: 'Boots',
      price: 35,
      onSale: true,
      topSale: true,
      outOfStock: false,
      image: '/images/products/men-boots.5.1.jpg',
      starsRating: 5,
    },
    {
      id: '5',
      quantity: 1,
      type: 'Men',
      name: 'The North Face',
      category: 'Boots',
      price: 35,
      onSale: true,
      topSale: true,
      outOfStock: false,
      image: '/images/products/boots-1.jpg',
    },
    {
      id: '6',
      quantity: 1,
      type: 'Men',
      name: 'The North Face',
      category: 'Boots',
      price: 35,
      onSale: true,
      topSale: false,
      outOfStock: false,
      image: '/images/products/boots-1.jpg',
    },
    {
      id: '7',
      quantity: 1,
      type: 'Men',
      name: 'The North Face',
      category: 'Boots',
      price: 35,
      onSale: true,
      topSale: false,
      outOfStock: false,
      image: '/images/products/boots-1.jpg',
    },
    {
      id: '8',
      quantity: 1,
      type: 'Men',
      name: 'The North Face',
      category: 'Boots',
      price: 35,
      onSale: true,
      topSale: false,
      outOfStock: false,
      image: '/images/products/men-boots.1.1.png',
    },
    {
      id: '9',
      quantity: 1,
      type: 'Women',
      name: 'The North Face',
      category: 'Boots',
      price: 35,
      onSale: false,
      outOfStock: false,
      image: '/images/products/women-boots.1.1.jpg',
      starsRating: 4,
    },
    {
      id: '10',
      quantity: 1,
      type: 'Women',
      name: 'The North Face',
      category: 'Boots',
      price: 35,
      onSale: false,
      outOfStock: false,
      image: '/images/products/boots-1.jpg',
      starsRating: 4,
    },
    {
      id: '11',
      quantity: 1,
      type: 'Women',
      name: 'The North Face',
      category: 'Boots',
      price: 35,
      onSale: false,
      outOfStock: false,
      image: '/images/products/boots-1.jpg',
    },
    {
      id: '12',
      quantity: 1,
      type: 'Women',
      name: 'The North Face',
      category: 'Boots',
      price: 35,
      onSale: false,
      outOfStock: false,
      image: '/images/products/boots-1.jpg',
    },
    {
      id: '13',
      quantity: 1,
      type: 'Women',
      name: 'The North Face',
      category: 'Boots',
      price: 35,
      onSale: false,
      outOfStock: false,
      image: '/images/products/boots-1.jpg',
    },
    {
      id: '14',
      quantity: 1,
      type: 'Women',
      name: 'The North Face',
      category: 'Boots',
      price: 35,
      onSale: false,
      outOfStock: false,
      image: '/images/products/boots-1.jpg',
    },
    {
      id: '15',
      quantity: 1,
      type: 'Women',
      name: 'The North Face',
      category: 'Boots',
      price: 35,
      onSale: true,
      oldPrice: 55,
      outOfStock: false,
      image: '/images/products/boots-1.jpg',
    },
    {
      id: '16',
      quantity: 1,
      type: 'Women',
      name: 'The North Face',
      category: 'Boots',
      price: 35,
      onSale: true,
      outOfStock: false,
      image: '/images/products/boots-1.jpg',
    },
  ],
  user: null,
  cart: [],
};

export default initialState;
